#define SERIAL_SPEED 115200

#define FAN_SPEED_MAX 9
#define FAN_SPEED_MIN 0

#define MM_COUNT 3
#define LEVEL_COUNT MM_COUNT

#define DEFAULT_EMIT_SPEED_LEVEL 5

#define EMIT_SPEED_LEVEL_LEFT DEFAULT_EMIT_SPEED_LEVEL
#define EMIT_SPEED_LEVEL_MIDDLE DEFAULT_EMIT_SPEED_LEVEL
#define EMIT_SPEED_LEVEL_RIGHT DEFAULT_EMIT_SPEED_LEVEL

#define LED_FLOAT_STRIP_COUNT 6
#define LED_STRIP_COUNT 8

#define LED_COUNT_DASHBOARD 144
#define LED_COUNT_FINS 60					// 2 x 30
#define LED_COUNT_CABLE_HOLDER 144			// 2 x 72
#define LED_COUNT_MIDDLE_STRIP 67
#define LED_COUNT_HEADLIGHTS_LEFT 58
#define LED_COUNT_HEADLIGHTS_RIGHT LED_COUNT_HEADLIGHTS_LEFT
#define LED_COUNT_HEADLIGHTS_AMB_LEFT 56
#define LED_COUNT_HEADLIGHTS_AMB_RIGHT LED_COUNT_HEADLIGHTS_AMB_LEFT

#define LED_DEFAULT_BRIGHTNESS 4
#define LED_BRIGHTNESS_OFF 0
#define LED_BRIGHTNESS_MAX 9

#define LED_BRIGHTNESS_DASHBOARD LED_DEFAULT_BRIGHTNESS
#define LED_BRIGHTNESS_FINS LED_DEFAULT_BRIGHTNESS
#define LED_BRIGHTNESS_CABLE_HOLDER LED_DEFAULT_BRIGHTNESS
#define LED_BRIGHTNESS_MIDDLE_STRIP LED_BRIGHTNESS_MAX
#define LED_BRIGHTNESS_HEADLIGHTS_LEFT LED_DEFAULT_BRIGHTNESS
#define LED_BRIGHTNESS_HEADLIGHTS_RIGHT LED_DEFAULT_BRIGHTNESS
#define LED_BRIGHTNESS_HEADLIGHTS_AMB_LEFT LED_DEFAULT_BRIGHTNESS
#define LED_BRIGHTNESS_HEADLIGHTS_AMB_RIGHT LED_DEFAULT_BRIGHTNESS

#define BLEND_OFF -1

#define COLOR_COUNT 10		// first one is reserved for default color

#define LED_COLOR_DEFAULT 0

#define LED_COLOR_0 CRGB::Red
#define LED_COLOR_1 CRGB::DeepPink
#define LED_COLOR_2 CRGB::Purple

#define LED_COLOR_3 CRGB::RoyalBlue
#define LED_COLOR_4 CRGB::DeepSkyBlue
#define LED_COLOR_5 CRGB::LightGreen

#define LED_COLOR_6 CRGB::Gold
#define LED_COLOR_7 CRGB::Orange
#define LED_COLOR_8 CRGB::GhostWhite