#define SERIAL_SPEED 9600

#define LEVEL_COUNT 3

#define FAN_SPEED_MAX 9
#define FAN_SPEED_MIN 0

#define MM_COUNT 3

#define LED_STRIP_COUNT 6

#define LED_COUNT_DASHBOARD 144
#define LED_COUNT_FINS 100
#define LED_COUNT_CABLE_HOLDER 120
#define LED_COUNT_HEADLIGHTS 100
#define LED_COUNT_HEADLIGHTS_AMB 80
#define LED_COUNT_MIDDLE_STRIP 80

#define LED_DEFAULT_BRIGHTNESS 128

#define COLOR_COUNT 1
#define LED_COLOR_0 CRGB::DarkRed
